services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15

  cert_app:
    build: .
    depends_on:
      cassandra:
        condition: service_healthy
    stdin_open: true
    tty: true

  cert_tests:
    build: .
    depends_on:
      cassandra:
        condition: service_healthy
    command: ["./build/cert_tests"]
